### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jmbeach** [matthistuff/amazon#1]
What permissions does the AWS account need in order for this to work?

**Comment by jmbeach** [comment]
Nevermind. Didn't pay attention to "Amazon Product Advertising API"

**Comment by matthistuff** [comment]
Hey @jmbeach glad it did clear up for you. Please keep in mind that I didn't touch this project in a long time and probably wont for the foreseeable future. Not sure if it even builds with a current Go version.

**Comment by jmbeach** [comment]
Aw dang. Well I have it working with the latest release. Thanks for the work
